spring.application.name=farmacia
spring.config.import=optional:file:.env[.properties]
server.port=${SERVER_PORT:8060}

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

app.jwt.secret=${JWT_SECRET}
app.jwt.expiration-minutes=${JWT_EXPIRATION_MINUTES:60}
app.cors.allowed-origins=${ALLOWED_ORIGINS:http://localhost:4200,http://127.0.0.1:4200}
