spring.application.name=farmacia
server.port=${SERVER_PORT:8060}

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/farmacia_db?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:pablogirao}

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

app.jwt.secret=${JWT_SECRET:MiClaveJWTMuySeguraParaFarmacia2026Backend}
app.jwt.expiration-minutes=${JWT_EXPIRATION_MINUTES:60}
app.cors.allowed-origins=${ALLOWED_ORIGINS:http://localhost:4200,http://127.0.0.1:4200}
